tmgmt.translator.settings.permission:
  type: mapping
  label: Settings for the Permission translator
  mapping:
    permission:
      type: string
      label: The permission needed for this translator

field.value.oe_translation_entity_revision_type_item:
  type: mapping
  label: Default value
  mapping:
    entity_id:
      type: string
      label: Entity ID
    entity_revision_id:
      type: string
      label: Entity Revision
    entity_type:
      type: string
      label: Entity Type

oe_translation.oe_translation_request_type.*:
  type: config_entity
  label: 'Translation Request type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'

field.value.oe_translation_language_with_status:
  type: mapping
  label: Default value
  mapping:
    langcode:
      type: string
      label: Language code
    status:
      type: string
      label: The status
