field.value.oe_translation_entity_revision_type_item:
  type: mapping
  label: Default value
  mapping:
    entity_id:
      type: string
      label: Entity ID
    entity_revision_id:
      type: string
      label: Entity Revision
    entity_type:
      type: string
      label: Entity Type

field.formatter.settings.oe_translation_entity_revision_type_formatter:
  type: mapping
  label: 'Entity revision with type formatter settings'
  mapping:
    link:
      type: boolean
      label: 'Whether to display as link'

oe_translation.oe_translation_request_type.*:
  type: config_entity
  label: 'Translation Request type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'

field.value.oe_translation_language_with_status:
  type: mapping
  label: Default value
  mapping:
    langcode:
      type: string
      label: Language code
    status:
      type: string
      label: The status

oe_translation.settings:
  type: config_object
  mapping:
    translation_source_embedded_fields:
      label: 'Embedded fields'
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: boolean
    translation_source_allowed_formats:
      type: sequence
      label: 'Allowed formats'
      sequence:
        type: string
        label: Format ID
