tmgmt.translator.settings.permission:
  type: mapping
  label: Settings for the Permission translator
  mapping:
    permission:
      type: string
      label: The permission needed for this translator

field.value.oe_translation_entity_revision_type_item:
  type: mapping
  label: Default value
  mapping:
    entity_id:
      type: string
      label: Entity ID
    entity_revision_id:
      type: string
      label: Entity Revision
    entity_type:
      type: string
      label: Entity Type

field.value.oe_translation_translation_sync:
  type: mapping
  label: Default value
  mapping:
    type:
      type: string
      label: Type
    configuration:
      type: string
      label: Configuration

oe_translation_request.oe_translation_request_type.*:
  type: config_entity
  label: 'Translation Request type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
