oe_translation_remote.remote_translation_provider.*:
  type: config_entity
  label: 'Remote Translator Provider config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    plugin:
      type: string
      label: 'Remote translation provider plugin'
    plugin_configuration:
      type: oe_translation_remote.remote_translation_provider.plugin.[%parent.plugin]
      label: 'Remote translation provider plugin settings'

oe_translation_remote.remote_translation_provider.plugin.*:
  type: mapping
  label: 'Plugin configuration'

field.value.oe_translation_remote_translated_data:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

oe_translation.oe_translation_request_type.*.third_party.oe_translation_remote:
  type: mapping
  label: 'Remote translation settings'
  mapping:
    remote_bundle:
      type: boolean
      label: 'Remote bundle'
