field.value.oe_transalation_epoetry_contact:
  type: mapping
  label: Default value
  mapping:
    contact_type:
      type: string
      label: Contact type
    contact:
      type: string
      label: Contact

oe_translation_remote.remote_translation_provider.plugin.epoetry:
  type: mapping
  label: Plugin configuration for the ePoetry plugin
  mapping:
    contacts:
      type: sequence
      label: Contacts
      sequence:
        type: string
        label: Contact (keyed by type of contact)
    auto_accept:
      type: boolean
      label: Auto-accept translations
    title_prefix:
      type: string
      label: Title prefix
    site_id:
      type: string
      label: The site ID
    language_mapping:
      type: sequence
      label: The language mapping
      sequence:
        type: string
        label: The language code

views.filter.oe_translation_epoetry_request_id_filter:
  type: views.filter.string
  label: Request ID filter

views.filter.oe_translation_epoetry_target_languages_filter:
  type: views.filter.in_operator
  label: Target language filter

views.field.oe_translation_epoetry_target_languages_with_tooltip:
  type: views_field
  label: 'Target languages with tooltip'

field.storage_settings.oe_translation_language_with_date:
  type: mapping
  label: 'Datetime settings'
  mapping:
    datetime_type:
      type: string
      label: 'Date type'
